### PR TITLE
Add support for default architecture

### PR DESCRIPTION
**Pull request by dhoppe**
Please provide a default value for `architecture` otherwise you would end up with an empty `./public/pool` directory.

### CODE REVIEW

**Comment by aerostitch** [comment]
Hi @dhoppe ,

Thanks for the PR.
Could you update the specs to make the tests pass please?

Thanks

**Comment by dhoppe** [comment]
No problem. I always forget to activate the pre-commit-hook. I'll take care of it tonight.

**Comment by aerostitch** [comment]
Thanks. Don't forget to update the README.md too please.

**Comment by dhoppe** [comment]
Done.

**Comment by aerostitch** [comment]
Sounds good. Thanks a lot! :)

**Pull request merged**
