### PR TITLE
Fix syntax

### LINKED ISSUE #21: Aptly service doesn't start
aptly-api starts just fine, but aptly webserver doesn't

### PR DESCRIPTION
**Pull request by dhoppe**
Please fix syntax, because the additional chars break the init script. This will fix #21.

### CODE REVIEW

**Comment by aerostitch** [comment]
What was wrong with the double quotes? You had an error?

**Comment by rhoml** [comment]
I can confirm that this extra characters break aptly start once they are removed aptly start normally

**Comment by dhoppe** [comment]
There is no error message, but the aptly.pid contains a process id which does not exist and the init script for aptly-api do not use double quotes and works as expected.

**Comment by aerostitch** [comment]
Sounds good then. I never noticed it before. Thanks for pointing it out!

**Pull request merged**
